Fix of details for UG & DG
AY2324S1-CS2103-W14-3/tp pull request #148
Opened 2023-11-02 12:56 UTC by mamayuan

Fix some consistency issues.

2023-11-02 13:25 UTC, rayshawntan approved these changes

2023-11-02 14:17 UTC, Cloud7050 requested changes

2023-11-02 14:17 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* **UI (User Interface)**: The space where interactions between humans and the software occur. The goal of this interaction is to allow effective operation and control of the machine from the human e
Glossary idea: GUI. Since it is used elsewhere in the docs too.

2023-11-02 14:17 UTC, Cloud7050 commented on docs/UserGuide.md
> +Alternatively, you can enter `help`, press <kbd>F1</kbd> or click Help → Help in the top toolbar.
I don't think we need to re-mention the command as that's the default way to use the functionality. Akin to exit below. The alternate methods are just documented for completeness.

2023-11-02 14:17 UTC, Cloud7050 commented on docs/UserGuide.md
> +Searches and displays contacts with tag matching the given keywords (case-insensitive).
Previously I just merged, but since we're editing this line, maybe the wording for the "with tag matching" part could be improved?

2023-11-02 14:17 UTC, Cloud7050 commented on docs/UserGuide.md
> +e.g. Keyword `john` will match the name `John`.
Good catch.

2023-11-02 17:13 UTC, Cloud7050 commented
Linking #148.

2023-11-03 00:48 UTC, Cloud7050 commented on docs/UserGuide.md
> +Searches and displays contacts with tag matching the given keywords (case-insensitive).
This is now irrelevant after merging #149.

2023-11-03 00:49 UTC, Cloud7050 commented
This PR is docs only, so I'm going to move ahead with the JAR and wrapup.

2023-11-03 01:00 UTC, Cloud7050 commented
Moving to next milestone so that we can wrap up v1.3b, but we could still try to merge this today before the PE dry run if we want.

2023-11-03 07:44 UTC, Cloud7050 approved these changes

2023-11-03 07:44 UTC, merged