Enhancement of UG
AY2324S1-CS2103-W14-3/tp pull request #191
Opened 2023-11-08 02:36 UTC by mamayuan

Specified `INDEX` we use is 1-based.

Added a command summary table at the end.

2023-11-08 03:35 UTC, Cloud7050 requested changes

2023-11-08 03:35 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +1. Add a boolean field to deleteCommand class to indicate whether user has entered duplicate indicies in the command. Display an extra message to remind the user of it.
- Could probably change capitalisation of `DeleteCommand` and add formatting
- Typo in "indicies"
- Do we need further elaboration? If the planned enhancement does not address the feature flaw enough, testers may still re-report a flaw with the planned enhancement during the PE

2023-11-08 03:35 UTC, Cloud7050 commented on docs/UserGuide.md
> +- `INDEX` used in commands is always 1-based.
I was thinking, if we address the other issue about having a labelled image explaining parts of the UI, then the topic of indices should already be made clearer.

But no harm adding more detail as well. However, should we merge this info into the part that explains indices instead?

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/d7c70ea2-cd98-4042-9c37-51988213640e)

Come to think of it, isn't it already pretty clear whether the index is 0 or 1-based from that explanation? 0 is not positive. To what extent do we need to elaborate, if at all?

There was an issue about this topic (#172), I think it was more so about the in-app output, but that output is meant to be short while the full details are in the UG. A bit like `git help`.

2023-11-08 03:35 UTC, Cloud7050 commented on docs/UserGuide.md
> +## Command Summary
For consistency, we could add a `---` hr above this new h2 section. We could also not capitalise the "s" in "Summary".

2023-11-08 03:39 UTC, Cloud7050 commented
Btw, does this PR target any specific currently open issue(s)?

2023-11-08 05:03 UTC, mamayuan commented
> Btw, does this PR target any specific currently open issue(s)?

The summary table is just something I saw in other team's UG. I think it's a good to have/ I remember one of the testers also mentioned to better include a summary but I cant find it now.

2023-11-08 05:04 UTC, mamayuan commented on docs/UserGuide.md
> +- `INDEX` used in commands is always 1-based.
Yea I agree. I think the tester overlooked this part. i have removed the additional clarification from the PR.

2023-11-08 05:06 UTC, mamayuan commented on docs/DeveloperGuide.md
> +1. Add a boolean field to deleteCommand class to indicate whether user has entered duplicate indicies in the command. Display an extra message to remind the user of it.
Yup changed it.

2023-11-09 12:01 UTC, Cloud7050 approved these changes
Approving if you are satisfied with the level of elaboration.

One thing I noticed, we could probably use the term "warning" as I think we will be adding more such warnings as planned enhancements. Ie "an additional message to remind the user" → "a warning in the output".

2023-11-09 13:41 UTC, rayshawntan approved these changes

2023-11-09 13:42 UTC, merged