AlternateContact and Phone BugFix and Feature Enhancements
AY2324S1-CS2103-W14-3/tp pull request #193
Opened 2023-11-08 08:28 UTC by rayshawntan

This PR clears the bugs that are caused by the regex in `Phone.java` and `AlternateContact.java`. This corrects the values that can be accepted by both. UG and `Messages.java` are updated to give better clarity on what can be accepted and what is not.

Closes #166 , #178 , #192

2023-11-09 12:05 UTC, Cloud7050 requested changes

2023-11-09 12:05 UTC, Cloud7050 commented on src/main/java/swe/context/logic/Messages.java
> +            + "Whitespace is not supported for both SocialMedia and Username and Username only supports ._-";
They may count enhancing the message as a feature enhancement.

2023-11-09 12:05 UTC, Cloud7050 commented on src/main/java/swe/context/model/contact/Phone.java
>       * Requires starting with at least 3 of digits.
This Javadoc is now outdated. There may be other places that are now outdated.

2023-11-09 12:06 UTC, Cloud7050 commented on src/main/java/swe/context/logic/Messages.java
> +            + "Whitespace is not supported for both SocialMedia and Username and Username only supports ._-";
Also, is there meant to be a `%n` newline?

2023-11-09 12:13 UTC, rayshawntan commented on src/main/java/swe/context/logic/Messages.java
> +            + "Whitespace is not supported for both SocialMedia and Username and Username only supports ._-";
> They may count enhancing the message as a feature enhancement.

Yeap, rereading on what constitutes as a feature enhancement, this definitely seems more like an enhancement. Have removed it.

2023-11-09 12:14 UTC, rayshawntan commented on src/main/java/swe/context/model/contact/Phone.java
>       * Requires starting with at least 3 of digits.
Have amended this.

2023-11-09 13:55 UTC, Cloud7050 commented
> Closes #166 , #178 , #192

Btw, the above only autocloses the first issue. They would need the "closes" keyword repeated for all of them.

2023-11-09 14:19 UTC, Cloud7050 requested changes

2023-11-09 14:19 UTC, Cloud7050 commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
We may be able to simplify this if we want (refactoring alongside the fix). Draft: `^[a-zA-Z\\d]+: [a-zA-Z\\d\\._-]+$`. I have not checked this. But aside from the Java string escapes, this is a useful site: https://regexr.com/.

Potential bug: If we allow any whitespace (`\s`), users may do something weird like put a zero-width space. It would look different from the other alternates. It may also fail unit test if we test using a newline.

2023-11-09 14:19 UTC, Cloud7050 commented on docs/UserGuide.md
> +(Adds a contact with the name `John Doe`, phone `98765432`, email `john.doe@email.com`, note `Likes SE`, tags `NUS` and `CS2103 course` and alternate contact `Telegram: JohnDoe`)
The note in the second part is missing the fullstop.

2023-11-09 14:19 UTC, Cloud7050 commented on docs/UserGuide.md
> +Do note at this moment whitespace is not supported for `TYPE` and `USERNAME` and `USERNAME` supports only `._-`.
- Does  "and `USERNAME` and `USERNAME`" read a bit strangely? Should we add something like a comma?
- Testers may be able to report a bug if it sounds like `USERNAME` *only* supports `._-` (maybe specify that those are the only *special characters* aside from alnum supported or something)

2023-11-09 14:19 UTC, Cloud7050 commented on docs/UserGuide.md
> +Phone numbers must contain at least 3 digits. Alphabets and special characters are not accepted.
Should we be clearer in case testers still try to make reports? The regex is changed to strictly only allow digits.

2023-11-09 14:19 UTC, Cloud7050 commented on src/main/java/swe/context/model/contact/Phone.java
> +    public static final String REGEX_VALID = "^\\d{3,}";
For consistency, perhaps we should keep the ending `$` (matches end of string, like an opposite of `^`). Java's `matches()` matches the full string, but `find()` does not.

2023-11-09 14:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +actually exist some part of the world. We also intend to allow users to include the `+` prefix to allow users to indicate
Typo in "number that actually exist some part of the world".

2023-11-09 14:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +country codes as well. The invalid message `Phone numbers must start with at least 3 digits.` as a result will need to be
That message is the way it is because users were allowed to put other characters after those 3 digits. I think if we are changing the regex due to a bug, it is then fitting to also fix the message accordingly. (The planned enhancement may then further edit the message again.)

2023-11-09 14:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +updated to reflect on this change.
Is there a typo in the "on" of "reflect on"?

2023-11-09 14:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* The current implementation of `AlternateContact` does not allow users to include whitespace in `TYPE` and `USERNAME`
Typo where "and `USERNAME`" is repeated twice.

2023-11-09 14:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +and `USERNAME` only supports `._-` symbols. We intend to allow users to include whitespace as well as more `USERNAME`
Similar to other comments, is there room to be more specific to avoid testers trying to report flaws in the planned enhancement?

- Eg "symbols" is mentioned, which we can understand means special characters alongside the alnum, but will testers interpret it the same?
- Eg how will testers interpret "more `USERNAME`"?

2023-11-09 14:59 UTC, rayshawntan commented on docs/UserGuide.md
> +(Adds a contact with the name `John Doe`, phone `98765432`, email `john.doe@email.com`, note `Likes SE`, tags `NUS` and `CS2103 course` and alternate contact `Telegram: JohnDoe`)
Ah, my bad. Have amended this.

2023-11-09 16:57 UTC, rayshawntan commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
> We may be able to simplify this if we want (refactoring alongside the fix). Draft: `^[a-zA-Z\\d]+: [a-zA-Z\\d\\._-]+$`. I have not checked this. But aside from the Java string escapes, this is a useful site: https://regexr.com/.

I don't think this is possible to be done without risking chance of this considering as a feature enhancement.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/83902023/b723c6d3-bdbb-4368-9b22-c9e747465f7d)

> Potential bug: If we allow any whitespace (`\s`), users may do something weird like put a zero-width space. It would look different from the other alternates. It may also fail unit test if we test using a newline.
 
`\s` does not allow zero-width space from my understanding.

2023-11-09 19:26 UTC, Cloud7050 commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
I feel like it fits this pointer. We are not tweaking the check's behaviour (aside from the bug fix), rather, we are refactoring the regex, ie refactoring the code:

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/65e1d168-4d1b-44d3-a8ea-c3232977583a)

Personally I think it is safe to do.

---

TIL `\s` does not match zws, thanks. Perhaps another example would be pasting in `	` (tab) to sabotage the application. The alternate would still look wider than the others, since only one whitespace character is allowed. And I feel the newline point still stands.

Names on the other hand (and by extension, tags) only allow normal spaces.

2023-11-09 19:37 UTC, Cloud7050 commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/f90ae0e3-1b4f-4290-af1b-870f3a8b64e9)

2023-11-09 19:49 UTC, Cloud7050 commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/ec61d111-cca9-43bf-b632-099e9c572199)

(Comparison to PR regex, with added `$` to behave like `matches()`)

2023-11-09 19:51 UTC, Cloud7050 commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
During testing, I think I found a regression with the PR regex. Since everything in the capturing group is optional, empty values are once again allowed:

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/297da0a4-8d76-4783-bffd-6c4124fc93eb)

2023-11-10 01:19 UTC, rayshawntan commented on src/main/java/swe/context/model/alternate/AlternateContact.java
> +            "^[a-zA-Z\\d]+(?:[a-zA-Z\\d]+)*" + ":\\s([._-]?[a-zA-Z0-9]?)+";
hmm, since its okay, will update the regex then

2023-11-10 03:01 UTC, Cloud7050 commented on docs/UserGuide.md
> +Do note at this moment whitespace is not supported for `TYPE` and `USERNAME`. `USERNAME` supports only special characters `.`, `_` and `-`.
Re: Taking this line on its own:

> `USERNAME` supports only special characters `.`, `_` and `-`.

When read a certain way, it could sound like username literally only supports those 3 characters and nothing else.

As we are refactoring the regex to be clearer, would it be good to clarify w.r.t. alnum?

2023-11-12 22:14 UTC, Cloud7050 requested changes

2023-11-12 22:14 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +   whitespace in`TYPE` and `USERNAME`. `USERNAME` will also be enhanced to include other special characters that are not
> in`TYPE`

There is a missing space here.

2023-11-12 22:15 UTC, Cloud7050 approved these changes

2023-11-13 12:08 UTC, bwangpj approved these changes

2023-11-13 12:09 UTC, merged