Update user stories
AY2324S1-CS2103-W14-3/tp pull request #201
Opened 2023-11-09 13:48 UTC by mamayuan

Removed unused user stories in DG according to our previous discussion. 
Added a few more user stories based on our product.
Quick fix to delete example in UG.
Possible to include more user stories. Let me know if yall can think of any. I'll add in :)

[Closes #159 .]
[Closes #130 .]

2023-11-09 14:42 UTC, mamayuan commented
I'm sorry guys, I forgot to create a new branch for code refactoring. So they are also included in this PR... Not many changes, hopefully it is not too confusing to include two tasks in one here...

2023-11-09 14:46 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> -| `*`      | busy user                       | use icons to denote certain contact information                                      | identify the information I want at a glance
Is it ok to keep this user story?

2023-11-09 14:46 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> -| `*`      | infrequent user                 | view a “cheatsheet” or help dialog for the text commands                             | remember some basic commands I may have forgotten
Similarly, is it ok to keep this?

See also https://github.com/AY2324S1-CS2103-W14-3/tp/issues/171#issuecomment-1793260253.

2023-11-09 14:46 UTC, Cloud7050 commented on docs/UserGuide.md
> +
I was initially thinking this would fit better as an "e.g." kind of line under L153.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/307551c8-fe3c-4cd9-886b-05e8ab2e8038)

For your consideration.

2023-11-09 14:56 UTC, Cloud7050 commented
> I'm sorry guys, I forgot to create a new branch for code refactoring. So they are also included in this PR... Not many changes, hopefully it is not too confusing to include two tasks in one here...

Ah I see. It should be possible to cherry pick the commits onto a new branch and then reset this branch to a few commits back, if you want to look into that.

2023-11-10 03:21 UTC, Cloud7050 commented
Did you mean to autoclose #93 instead of #130? I think the latter is still ongoing. I will edit the body for now.

2023-11-10 03:28 UTC, Cloud7050 requested changes

2023-11-10 03:28 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +| `*`      | infrequent user                 | view a “cheatsheet” or help dialog for the text commands                             | remember some basic commands I may have forgotten
I noticed the inverted commas here are "smart quotes" that programs like Word automatically replace in. Should we change these to normal quotes?

2023-11-10 03:28 UTC, Cloud7050 commented on docs/UserGuide.md
> +e.g. `delete 1 1` will only deletes the contact at index #`1`.
There is a typo in "deletes".

2023-11-10 03:32 UTC, mamayuan commented
> Did you mean to autoclose #93 instead of #130? I think the latter is still ongoing. I will edit the body for now.

Yup I was wrong

2023-11-10 03:40 UTC, mamayuan commented on docs/UserGuide.md
> +e.g. `delete 1 1` will only deletes the contact at index #`1`.
Thx! I've fixed it!

2023-11-10 03:41 UTC, mamayuan commented on docs/DeveloperGuide.md
> +| `*`      | infrequent user                 | view a “cheatsheet” or help dialog for the text commands                             | remember some basic commands I may have forgotten
ok done!

2023-11-10 03:42 UTC, mamayuan commented
> > I'm sorry guys, I forgot to create a new branch for code refactoring. So they are also included in this PR... Not many changes, hopefully it is not too confusing to include two tasks in one here...
> 
> Ah I see. It should be possible to cherry pick the commits onto a new branch and then reset this branch to a few commits back, if you want to look into that.

A bit tedious... I'll leave it like this first. The refactoring is not much.

2023-11-10 03:51 UTC, Cloud7050 commented
> A bit tedious... I'll leave it like this first. The refactoring is not much.

Aight.

---

I have not looked at the refactoring. But I think the docs part LGTM.

Neutral on removing the icons user story, I guess even if we remove it, we still have enough user stories. But adding icons (as a general idea) may still be a nice future feature.

2023-11-11 03:46 UTC, Cloud7050 commented
Also works towards #184.

2023-11-11 11:11 UTC, mamayuan commented
> | `*` | busy user | use icons to denote certain contact information | identify the information I want at a glance |



> > A bit tedious... I'll leave it like this first. The refactoring is not much.
> 
> Aight.
> 
> I have not looked at the refactoring. But I think the docs part LGTM.
> 
> Neutral on removing the icons user story, I guess even if we remove it, we still have enough user stories. But adding icons (as a general idea) may still be a nice future feature.

Yup added it back

2023-11-13 02:36 UTC, Cloud7050 approved these changes

2023-11-13 03:28 UTC, bwangpj approved these changes

2023-11-13 03:28 UTC, merged