Explain that 'empty' fields are not allowed
AY2324S1-CS2103-W14-3/tp pull request #207
Opened 2023-11-10 03:25 UTC by bwangpj

Explain in UG that 'empty' fields are not allowed, just to be safe!

2023-11-10 03:47 UTC, Cloud7050 requested changes

2023-11-10 03:47 UTC, Cloud7050 commented on docs/UserGuide.md
>  </div>
- Since we link back to this alert in `edit`, would it be clearer if we say that these empty tags/alternates are only not allowed when adding?
- For consistency, should we use the term "parameter" instead of "option"?
- This alert is a span, so all the sentences get combined into a paragraph. The individual sentences may read a bit oddly when strung together. Maybe convert it into a block of bullet points like some of the other longer alerts?

Draft something like:
```suggestion
<div markdown="block" class="alert alert-info">
:information_source: **About tags:**

- Duplicate tags are only counted once.

- Specifying empty tags (`t/` with no value) is not allowed when adding contacts. If you wish to specify no tags, you may simply leave out the `t/` parameter.
</div>
```

These comments could also apply to the alternate contact alert below.

2023-11-10 03:55 UTC, bwangpj commented on docs/UserGuide.md
>  </div>
ok done! I really need to look at what my intellij is doing with markdown files, somehow the formatting is all different...

2023-11-10 04:07 UTC, Cloud7050 requested changes

2023-11-10 04:07 UTC, Cloud7050 commented on docs/UserGuide.md
>  <div markdown="span" class="alert alert-info">
Re: Would need to change to `markdown="block"` or the bullet points are probably going to look very weird even if they work.

2023-11-13 02:11 UTC, Cloud7050 approved these changes

2023-11-13 02:13 UTC, Cloud7050 commented
Regarding e5f9068, we may not need to change the other existing spans to also be blocks. I think that may force the divs to retain newlines. The shorter alerts without bullet points could stay as spans in a single paragraph.

2023-11-13 02:21 UTC, Cloud7050 commented
Reference for how the alerts look as span vs div @ https://ay2324s1-cs2103-w14-3.github.io/tp/UserGuide.html

2023-11-13 02:39 UTC, Cloud7050 requested changes
https://github.com/AY2324S1-CS2103-W14-3/tp/pull/207#issuecomment-1807373768

2023-11-13 04:10 UTC, Cloud7050 approved these changes

2023-11-13 04:12 UTC, rayshawntan approved these changes

2023-11-13 04:12 UTC, merged