Update Use Cases
AY2324S1-CS2103-W14-3/tp pull request #211
Opened 2023-11-11 05:01 UTC by rayshawntan

Update use cases to include our current list of features.

2023-11-12 22:24 UTC, Cloud7050 requested changes

2023-11-12 22:24 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
Should we make this more general? Talking about indices restricts the IO method users may use. Eg what if the designer wants to allow users to specify a contact to edit via arrow keys?

2023-11-12 22:25 UTC, Cloud7050 commented
Works towards #130.

2023-11-13 01:51 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
Is it possible to do so thou? Considering arrow keys are being used by the `CommandBoxHistory`

2023-11-13 02:10 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
The initial example I typed was about clicking the contact, but that also has some grey area since the project has the whole typing-preferred constraint. I settled on the example of arrow keys (left/right arrow are "unbound"), but again that may not be the best example.

Overall iirc, use cases should not mention the kind of IO so that designers are free to decide that. This instance seems to restrict the way a user picks a contact to doing so by giving an index. Open to discussion.

2023-11-13 02:16 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
In this case, I could remove this and leave 2b.

2023-11-13 02:19 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
Maybe something like "An invalid contact to edit is specified"?

2023-11-13 02:54 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +* 2a. The given index is invalid.
This could work as well

2023-11-13 03:22 UTC, bwangpj approved these changes

2023-11-13 03:22 UTC, bwangpj commented on docs/DeveloperGuide.md
> +1. User requests to filter the list contacts.
Just nitpicking - should be "list of contacts", and maybe "filter the list of contacts by a given tag"

2023-11-13 04:09 UTC, Cloud7050 approved these changes

2023-11-13 04:09 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* 2a. An invalid contact to edit is specified
Some edited lines may no longer have consistent fullstops.

2023-11-13 04:13 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +* 2a. An invalid contact to edit is specified
Oops my bad

2023-11-13 04:20 UTC, merged