Add manual testing section to DG
AY2324S1-CS2103-W14-3/tp pull request #212
Opened 2023-11-11 15:29 UTC by mamayuan

Part of #130

2023-11-12 06:53 UTC, rayshawntan approved these changes

2023-11-12 22:34 UTC, Cloud7050 requested changes

2023-11-12 22:34 UTC, Cloud7050 commented on docs/DeveloperGuide.md
>     1. Re-launch the app by double-clicking the jar file.<br>
- PE instructions says to run the JAR file via the CLI instead of double-clicking, to ensure the correct Java version gets used.
- Retaining window settings came with AB3, but is just something we kept around.

![image](https://github.com/AY2324S1-CS2103-W14-3/tp/assets/44526554/a8a55a99-4152-4f30-9312-c5a72ee835ce)

2023-11-12 22:34 UTC, Cloud7050 commented on docs/DeveloperGuide.md
>  ### Deleting a contact
Would it be better to reorder this? Maybe above `exit`, and following the order of commands in the UG?

Course website deliverables mention "charting a path through the features".

2023-11-13 03:19 UTC, bwangpj approved these changes

2023-11-13 09:11 UTC, mamayuan commented on docs/DeveloperGuide.md
>     1. Re-launch the app by double-clicking the jar file.<br>
Thanks for the heads-up. I've made relevant edits

2023-11-13 10:11 UTC, Cloud7050 approved these changes

2023-11-13 10:11 UTC, merged