Update DG: Use Cases
AY2324S1-CS2103-W14-3/tp pull request #37
Opened 2023-10-03 16:01 UTC by rayshawntan

This implements the basic use cases that the user may face shall as adding contacts, deleting contacts and listing contacts.

Closes #13

2023-10-04 03:48 UTC, Cloud7050 requested changes

2023-10-04 03:48 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +* 2a. The given data is invalid.
Perhaps this should branch off 1a? This would be consistent with the deletion use case below, which also branches off the user's request (3a) as opposed to ConText's action.

I took a quick look at the course site and it also seems to branch off the request.

2023-10-04 03:48 UTC, Cloud7050 commented on docs/DeveloperGuide.md
>        Use case resumes at step 2.
Following on, if the above use case resumes at 1, should we similarly change to resume at 3 here?

2023-10-04 03:48 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +**Use case: List all contacts**
The above deletion use cases contains the listing use case. Are *extensions* applicable here?

2023-10-04 06:05 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +**Use case: List all contacts**
Whoops I mean *inclusion**

2023-10-04 14:42 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +* 2a. The given data is invalid.
Yea, I noticed that I should have branched off 1a instead. Thanks!

2023-10-04 14:48 UTC, Cloud7050 approved these changes

2023-10-05 08:54 UTC, mamayuan approved these changes

2023-10-05 08:54 UTC, mamayuan commented on docs/DeveloperGuide.md
> +1.  User request to add a contact
should be 'requests' lol

2023-10-05 09:51 UTC, merged