Rename Person to Contact
AY2324S1-CS2103-W14-3/tp pull request #67
Opened 2023-10-15 01:27 UTC by bwangpj

Rename all instances of Person to Contact in the functional and test code.

Renaming of documentation to follow soon.

2023-10-15 16:39 UTC, Cloud7050 requested changes
Thanks for changing all these files. I didn't read through every single file thoroughly, but I've commented on some things I noticed.

2023-10-15 16:39 UTC, Cloud7050 commented on LICENSE
> +Permission is hereby granted, free of charge, to any contact obtaining a copy
We should probably not edit the license. Guessing this is overzealous replace all.

2023-10-15 16:39 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +| `* * *`  | user                            | delete contacts                                                                      | remove my contact with that contact
Wording here now sounds weird.

2023-10-15 16:39 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +| `* *`    | user of many communication apps | enter info about various platforms that my contacts use                              | keep track of all the various ways I can contact the same contact
Ditto.

2023-10-15 16:39 UTC, Cloud7050 commented on src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
> +        JsonAdaptedContact person = new JsonAdaptedContact(BENSON);
There may be some leftover `person` variable names in the files.

2023-10-16 03:11 UTC, rayshawntan requested changes
Overall, I think it looks good! Just need to amend the parts Joel mentioned and the change the string name to all capital

2023-10-16 03:11 UTC, rayshawntan commented on src/main/java/seedu/address/logic/Messages.java
> +    public static final String MESSAGE_Duplicate_Contact_Exception = "Operation would result in duplicate contacts";
I think we didn't catch this previously when @mamayuan edited his PR but final String variables should be in all capitalized.

2023-10-16 07:36 UTC, rayshawntan approved these changes

2023-10-16 13:33 UTC, Cloud7050 approved these changes

2023-10-16 13:33 UTC, merged