[Week 9] Rename AB3/AddressBook to ConText
AY2324S1-CS2103-W14-3/tp pull request #71
Opened 2023-10-16 16:38 UTC by mamayuan

Renamed all naming/reference to AB3/AddressBook to ConText. I left out namings in the .puml files. These are files associated with diagrams like class diagrams and stuff. I am not sure whther they will be relevant in the future. We can make changes on them when we touch on that part.

Closes #4, closes #41.

2023-10-16 17:40 UTC, Cloud7050 requested changes
Just some initial thoughts, open for discussion.

Also, should we take the opportunity to rename the packages early?

2023-10-16 17:40 UTC, Cloud7050 commented on docs/DeveloperGuide.md
> +**`Main`** (consisting of classes [`Main`](https://github.com/se-edu/-level3/tree/master/src/main/java/seedu/address/Main.java) and [`MainApp`](https://github.com/se-edu/addressbook-level3/tree/maste
This link would now be broken. If there are not too many links to the SE repo's code, should we just remove all such links altogether?

2023-10-16 17:40 UTC, Cloud7050 commented on src/main/java/seedu/address/storage/StorageManager.java
> +    public StorageManager(ConTextStorage ConTextStorage, UserPrefsStorage userPrefsStorage) {
The Storage component is more like the one acting as our overall "ConText storage" for the app, where it handles both the contact list as well as the user preferences. I think we could adopt more intuitive naming, maybe `ContactList`, `ContactListStorage` etc.

2023-10-17 02:11 UTC, bwangpj commented on src/main/java/seedu/address/ui/HelpWindow.java
> +    public static final String USERGUIDE_URL = "https://se-education.org/ConText-level3/UserGuide.html";
We should change this to our own user guide URL.

2023-10-17 02:19 UTC, rayshawntan commented on docs/DeveloperGuide.md
> +**`Main`** (consisting of classes [`Main`](https://github.com/se-edu/-level3/tree/master/src/main/java/seedu/address/Main.java) and [`MainApp`](https://github.com/se-edu/addressbook-level3/tree/maste
I believe we still need the links, especially since its supposed to reference the code in the repo, especially since this is DG. I think better solution is to update the links to direct to our repo instead.

2023-10-17 13:44 UTC, mamayuan commented
> Just some initial thoughts, open for discussion.
> 
> Also, should we take the opportunity to rename the packages early?

Do i just rename the package altogether in this PR or separately?

2023-10-17 14:16 UTC, mamayuan commented
As Bryan has pointed out, I also fixed the link to our UserGuide. From what I observe, I think it is the only place to change. If I did not miss anything, I think we can close #41 as well with this PR :)

2023-10-17 14:17 UTC, mamayuan commented on src/main/java/seedu/address/ui/HelpWindow.java
> +    public static final String USERGUIDE_URL = "https://se-education.org/ConText-level3/UserGuide.html";
Good catch! Thanks!

2023-10-17 15:49 UTC, Cloud7050 commented
I would like to discuss the naming. Perhaps the original work item wasn't very clear.

## Old

- `AddressBook` implements `ReadOnlyAddressBook`, containing persons
- `JsonAddressBookStorage` implements `AddressBookStorage` , handling the JSON side of storing `ReadOnlyAddressBook` via `JsonSerializableAddressBook`
  - `StorageManager` implements `Storage`, handling AB3's storage via both `AddressBookStorage` and `UserPrefsStorage`
- `AddressBookParser` handles AB3's parsing by using individual command parsers

## Current PR

- `ConText` implements `ReadOnlyConText`, containing contacts
- `JsonConTextStorage` implements `ConTextStorage` , handling the JSON side of storing `ReadOnlyConText` via `JsonSerializableConText`
  - `StorageManager` implements `Storage`, handling ConText's storage via both `ConTextStorage` and `UserPrefsStorage`
- `ConTextParser` handles ConText's parsing by using individual command parsers

## Proposed?

- `ContactsManager` implements `Contacts`, containing contacts
- `JsonContactsStorage` implements `ContactsStorage` , handling the JSON side of storing `Contacts` via `JsonSerializableContacts`
  - `StorageManager` implements `Storage`, handling ConText's storage via both `ContactsStorage` and `UserPrefsStorage`
- `InputParser` handles ConText's parsing by using individual command parsers

I find it hard to express exactly why, but I feel we shouldn't use `ConText` as is in the class names. Though `context` would fit in the package name.

One reason pointed out above was how ConText refers to the app as a whole, but the current class named after it handles a subset of the app's storage - just the `Contact`s - as part of the overall storage component. The name on its own is a little uninformative in that it doesn't really explain what the class is for. This was not a problem for AB3 as `AddressBook` is more self-explanatory, so it could overlap with the cosmetic naming.

The capitalisation style of our name also makes it feel a bit clunky to use in our code, eg when trying to camel case it (see below).

---

Other things noted:

- Class was renamed to `JsonSerializableConText` but file is still `JsonSerializableAddressBook.java`
- At least one instance of variable name not being camel case: `public StorageManager(ConTextStorage ConTextStorage, ...`, where it should be `conTextStorage`

2023-10-17 16:08 UTC, Cloud7050 commented
> I do agree with you on the renaming the class files to context. I was reading through earlier and felt a bit weird seeing everything be named ConText. It doesn't feel very friendly from a new developer point of view. Maybe it would be better to rename `AddressBook` references as `ContactList` instead.

I worry if a `ContactList` that contains the existing `UniqueContactList` becomes ambiguous.

I also read [this SO answer](https://stackoverflow.com/a/542122/11536796), specifically its second bullet point, which made me wonder if the `ReadOnly` part of the interface names are too long compared to the shorter class names. So instead it came to mind to adopt some of the existing naming scheme where some interfaces' implementations have `Manager` appended.

2023-10-18 05:55 UTC, mamayuan commented
> I would like to discuss the naming. Perhaps the original work item wasn't very clear.
> 
> ## Old
> * `AddressBook` implements `ReadOnlyAddressBook`, containing persons
> * `JsonAddressBookStorage` implements `AddressBookStorage` , handling the JSON side of storing `ReadOnlyAddressBook` via `JsonSerializableAddressBook`
>   
>   * `StorageManager` implements `Storage`, handling AB3's storage via both `AddressBookStorage` and `UserPrefsStorage`
> * `AddressBookParser` handles AB3's parsing by using individual command parsers
> 
> ## Current PR
> * `ConText` implements `ReadOnlyConText`, containing contacts
> * `JsonConTextStorage` implements `ConTextStorage` , handling the JSON side of storing `ReadOnlyConText` via `JsonSerializableConText`
>   
>   * `StorageManager` implements `Storage`, handling ConText's storage via both `ConTextStorage` and `UserPrefsStorage`
> * `ConTextParser` handles ConText's parsing by using individual command parsers
> 
> ## Proposed?
> * `ContactsManager` implements `Contacts`, containing contacts
> * `JsonContactsStorage` implements `ContactsStorage` , handling the JSON side of storing `Contacts` via `JsonSerializableContacts`
>   
>   * `StorageManager` implements `Storage`, handling ConText's storage via both `ContactsStorage` and `UserPrefsStorage`
> * `InputParser` handles ConText's parsing by using individual command parsers
> 
> I find it hard to express exactly why, but I feel we shouldn't use `ConText` as is in the class names. Though `context` would fit in the package name.
> 
> One reason pointed out above was how ConText refers to the app as a whole, but the current class named after it handles a subset of the app's storage - just the `Contact`s - as part of the overall storage component. The name on its own is a little uninformative in that it doesn't really explain what the class is for. This was not a problem for AB3 as `AddressBook` is more self-explanatory, so it could overlap with the cosmetic naming.
> 
> The capitalisation style of our name also makes it feel a bit clunky to use in our code, eg when trying to camel case it (see below).
> 
> Other things noted:
> 
> * Class was renamed to `JsonSerializableConText` but file is still `JsonSerializableAddressBook.java`
> * At least one instance of variable name not being camel case: `public StorageManager(ConTextStorage ConTextStorage, ...`, where it should be `conTextStorage`

Just fixed issues listed in Other things noted

2023-10-18 06:31 UTC, Cloud7050 commented
Very strange bug indeed

2023-10-18 13:06 UTC, Cloud7050 requested changes
Quick comment for something I noticed.

Later review pending other changes as per the long comment above.

2023-10-18 13:06 UTC, Cloud7050 commented on src/test/java/seedu/address/model/ContactsManagerTest.java
> +                () -> contactsManager.getContactList().remove(0)
Does 8 space rule really apply here? Afaik it's used when wrapping, but not for nesting.

2023-10-18 13:45 UTC, Cloud7050 approved these changes
I'll approve this first so we can merge and avoid blocking other issues from the large amount of renames. I'll make a followup PR for some things I noticed as well as the test case stuff later.

2023-10-18 15:48 UTC, rayshawntan approved these changes

2023-10-18 15:48 UTC, merged

2023-10-18 17:04 UTC, Cloud7050 commented on src/test/java/seedu/address/model/ContactsManagerTest.java
> +                () -> contactsManager.getContactList().remove(0)
Fixed in #80.