[Week 9] Continue refining TestData
AY2324S1-CS2103-W14-3/tp pull request #81
Opened 2023-10-18 16:20 UTC by rayshawntan

Update 'TestData' and the corresponding test cases.

Closes #68.

2023-10-19 00:02 UTC, Cloud7050 requested changes

2023-10-19 00:02 UTC, Cloud7050 commented on src/test/java/seedu/address/testutil/TestData.java
>                              .build();
Just an initial review comment for something I noticed. I messed up the indentation for amy here.

2023-10-20 04:55 UTC, bwangpj approved these changes

2023-10-20 05:25 UTC, mamayuan approved these changes

2023-10-20 06:18 UTC, merged